# To install nginx ingress I used helm3:
#
# ```
# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm install ingress-nginx ingress-nginx/ingress-nginx
# ```
#
# To enable TLS challenge over HTTP, I created a new `cert-manager` namespace
# and proceeded to install cert manager with helm3 according to these two
# resources:
#
# - [https://cert-manager.io/docs/installation/kubernetes]
# - [https://github.com/geerlingguy/kubernetes-101/tree/master/episode-06]
#
# It seems that the k8s ecosystem is still rapidly evolving. Consult docs for
# k8s ingress nginx controller before installation.

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod # is how other resources refer to it
spec:
  acme:
    email: cluster@porkbrain.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-secret-prod
    solvers:
    - http01:
        ingress:
          class: nginx # created by the nginx installation

